// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gahvtknrhnyevhyaoiue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhaHZ0a25yaG55ZXZoeWFvaXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzYzMzksImV4cCI6MjA2MTM1MjMzOX0.i31c-H6USAjPylZRqfaQjsA47XU6hxfzTuaE4xIPAGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);